

task0: task0.cc
	g++ task0.cc -o task0
	./task0
task1: task1.cc
	g++ task1.cc -o task1
	./task1
task2: task2.cc
	g++ task2.cc -o task2
	./task2
task3: task3.cc
	g++ task3.cc -o task3
	./task3
task4: task4.cc
	g++ task4.cc -o task4
	./task4

