task1: task1.cpp
	g++ task1.cpp -o 1
	./1
task2: task2.cpp
	g++ task2.cpp -o 2
	./2
task3: task3.cpp
	g++ task3.cpp -o 3
	./3
task4: task4.cpp
	g++ task4.cpp -o 4
	./4
task5: task5.cpp
	g++ task5.cpp -o 5
	./5

clean:
	rm 1 2 3 4 5